# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
first_name: Robin
last_name: Manhaeve
email: robin.manhaeve@cs.kuleuven.be
description: > # this means to ignore newlines until "url:"
  KU Leuven postdoctoral researcher at the DTAI research group.
footer_text: > # Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  <a href="https://dtai.cs.kuleuven.be/" target="_blank">DTAI</a>.
  <a href="https://www.kuleuven.be/kuleuven/" target="_blank">KU Leuven</a>.
  

show_news: false
show_address: true
 
url: https://people.cs.kuleuven.be
baseurl: /~robin.manhaeve
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# KU Leuven integration
# -----------------------------------------------------------------------------
ku_leuven_personnel_number: "0117389"

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: rmanhaeve
twitter_username: ManhaeveRobin
linkedin_username: # your LinkedIn user name
scholar_userid: pQht1BIAAAAJ
orcid_id: 0000-0001-9907-7486
medium_username: # your Medium username
quora_username: # your Quora username

contact_note:

google_analytics: UA-XXXXXXXXX # out your google-analytics code



# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: false
    permalink: /news/:path/
  projects:
    output: false
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge #pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor, bin, oldpages]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# -----------------------------------------------------------------------------
# Scholar settings
# -----------------------------------------------------------------------------
use_scholar: false # Set this to true if you want to use jekyll-scholar instead of Lirias.

scholar:
    sort_by: year, month
    last_name: Manhaeve # Your last name, this enables underlining your name in your publications
    order: descending
    bibliography_template: bib
    bibtex_skip_fields: 
     - abstract
     - month_numeric
     - code
     - pdf
     - supp
     - slides
     - poster
     - arxiv
     - video

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
